# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='term',
            field=models.CharField(choices=[('IM', 'Immediate'), ('ST', '1-2 Years'), ('MT', '3-5 Years'), ('LT', '6+ Years')], default='IM', max_length=2),
        ),
    ]
